services:
  bernardo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guanaco_bernardo
    restart: unless-stopped
    ports:
      - "${BERNARDO_PROXY_PORT:-8080}:8080" #proxy
      - "${BERNARDO_UI_PORT:-8081}:8081" #ui
    volumes:
      - ./:/app
