services:
  bernardo:
    build:
      context: .
      dockerfile: .docker/bernardo/Dockerfile
    container_name: bernardo
    restart: unless-stopped
    ports:
      - "8080:8080" #proxy
      - "8081:8081" #ui
    volumes:
      - ./bernardo:/app
